{% set version = "2.6.0" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.mpimet.mpg.de/attachments/download/30182/cdo-{{ version }}.tar.gz
  sha256: 752d5cda6fa3fdb8a04dcea16af5918e5f9f54657d9a5d2e35ae34f5755c31d8

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - gnuconfig  # [unix]
    - llvm-openmp  # [osx]
    - make  # [unix]
    - python
  host:
    - llvm-openmp  # [osx]
    - jasper
    - libcurl
    - libnetcdf
    - hdf5
    - proj
    - eccodes
    - libuuid
    - udunits2
    - libxml2-devel
    - fftw
    - magics
  run:
    - llvm-openmp  # [osx]
    - jasper
    - libcurl
    - libnetcdf
    - hdf5
    - proj
    - eccodes
    - libuuid
    - udunits2
    - libxml2-devel
    - fftw
    - magics

test:
  files:
    - dummy.nc
  commands:
    - cdo -V
    - cdo -sinfo dummy.nc
    - cdo -graph,device=png,linewidth=1 -settaxis,2000-01-01,12:00:00,1days -expr,'t=sin(seq*3.141529/180.0)' -for,1,6000 t

about:
  home: https://code.mpimet.mpg.de/projects/cdo
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data'

extra:
  recipe-maintainers:
    - zklaus
    - akrherz
    - Try2Code
    - ocefpaf
