{% set version = "1.9.5rc3" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.mpimet.mpg.de/attachments/download/18117/cdo-{{ version }}.tar.gz
  sha256: 0c2b84c91065b34f59067f2ea4338b82a1232e47956f11878885fce20e4069d2
build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - jasper
    - libnetcdf 4.4.*
    - proj4 4.9.3
    - eccodes
    - udunits2
    - libxml2 2.9.*
    - fftw
    - cmor
    - json-c 0.12.1
    - ossuuid 1.6.2 0
  run:
    - jasper
    - libnetcdf 4.4*
    - proj4 4.9.3
    - eccodes
    - udunits2
    - libxml2 2.9.*
    - fftw
    - cmor
    - ossuuid 1.6.2 0

test:
  files:
    - dummy.nc
  commands:
    - cdo -h
    - cdo sinfo dummy.nc  # [linux]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data.'

extra:
  recipe-maintainers:
    - ocefpaf
