{% set version = "1.9.9" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.mpimet.mpg.de/attachments/download/23323/cdo-{{ version }}.tar.gz
  sha256: 959b5b58f495d521a7fd1daa84644888ec87d6a0df43f22ad950d17aee5ba98d

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
  host:
    - llvm-openmp  # [osx]
    - jasper
    - libnetcdf
    - hdf5
    - proj
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - ossuuid
  run:
    - llvm-openmp  # [osx]
    - jasper
    - libnetcdf
    - hdf5
    - proj
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - ossuuid

test:
  files:
    - dummy.nc
  commands:
    - cdo -h
    - cdo sinfo dummy.nc

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0
  license_file: COPYING
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data'

extra:
  recipe-maintainers:
    - Try2Code
    - ocefpaf
