{% set version = "1.9.7.1" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.mpimet.mpg.de/attachments/download/20124/cdo-{{ version }}.tar.gz
  sha256: 3771952e065bcf935d43e492707370ed2a0ecb59a06bea24f9ab69d77943962c

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
  host:
    - llvm-openmp  # [osx]
    - jasper
    - libnetcdf
    - proj4
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - ossuuid
  run:
    - llvm-openmp  # [osx]
    - jasper
    - libnetcdf
    - proj4
    - eccodes
    - udunits2
    - libxml2
    - fftw
    - ossuuid

test:
  files:
    - dummy.nc
  commands:
    - cdo -h
    - cdo sinfo dummy.nc

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0
  license_file: COPYING
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data'

extra:
  recipe-maintainers:
    - Try2Code
    - ocefpaf
