{% set version = "1.9.0" %}

package:
  name: cdo
  version: {{ version }}

source:
  url: https://code.zmaw.de/attachments/download/15187/cdo-{{ version }}.tar.gz
  sha256: df367f8c3abf4ab085bcfc61e0205b28a5ecc69b7b83ba398b4d3c874dd69008

build:
  number: 0
  skip: True  # [win32]

requirements:
  build:
    - posix  # [win]
    - jasper  # [linux]
    - libnetcdf 4.4.*
    - proj4 4.9.3
    - util-linux  # [linux]
    - ecmwf_grib  # [linux]
    - udunits2
    - libxml2 2.9.*
    - fftw  # [linux]
    - m2w64-fftw  # [win]
    - m2w64-toolchain  # [win]
  run:
    - jasper  # [linux]
    - libnetcdf 4.4.*
    - proj4 4.9.3
    - libgcc  # [linux]
    - util-linux  # [linux]
    - ecmwf_grib  # [linux]
    - udunits2
    - libxml2 2.9.*
    - fftw  # [linux]
    - m2w64-fftw  # [win]

test:
  files:
    - dummy.nc
  commands:
    - cdo -h
    - cdo sinfo dummy.nc  # [not osx]
    - conda inspect linkages -p $PREFIX cdo  # [not win]
    - conda inspect objects -p $PREFIX cdo  # [osx]

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data.'

extra:
  recipe-maintainers:
    - ocefpaf
