appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ECcrSmpXUhCvrwFB0I/jo/fZybNkxn0wIvKqiw2267ttOgFIixBHCsvR5BPr5eN3aHh3kfmgW5SUbdHXq8qNNwuRefZygNJ3Lrz8KwcLagChp+LEVE7YNyAveJ1T6H/6INEvmhWlfR0KWMyrfwCluyPzOsOmidevaeczL4+mbdCqvFxCzq2EJKkKnRe5XO9jr/n7Hk2PNxBXtTvT8dtK5pldLNg3fTPTnJDbGSSlPWOAPkYg9i6nTbSdj4mvDeZpqaAP0ew1dJC/FvPvaLbKY4WkT8KllOxCEDzDyByLRqNOo/fqQJH9t/MoOVVhFUEFwwkpHEUZxpLR/H4rRWY8HO2UsSRNe5xlk7EcqYa0NuSClq7NtiIpepkiYWRLNgjhOee69EIC4vp0fiR9W/dh4viuqlKPRAhIdn2sqpSdWH8RG6aTgJA/Y8ASisUiRZI9enJ9eSOvZi1uvJ+p9Ps2iCrWd2rqI4rIfOnveM4mV4SYxPdWF34EHePoRI1G/TtTqT6E5K1je+8dS4JFtt7Fh1A2BJWRqV/Plbi+S4NeGYle3ZOeQkMxagvl7CFwWmcFKMz0m1Gv64erS5H+Tk+RNNP1nDccHPf/asEr0H+/TzDIjUDOMO2gQaGs2OVSZPlO0dl5DgDAqyiQq6L5rFOUVsMl0Iz1T/J2yVTnFb07ykk=}
